# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dADQ7m6hr1FBFtt8tK9nKi0Op6jvPC57
"""

import numpy as np
import matplotlib.pylab as plt

# Malla cúbica que contiene las condiciones iniciales del sistema, en el interior se encontrará el huevo esférico.

#Mis unidades de medida serán milímetros

def radio(z,r):
  return np.sqrt((r**2)-(z**2))

n = 5                                          #Tamaño de los vectores
r=1                                             #Radio del huevo
z = np.linspace(-r,r,n)                       #Arreglo de puntos de z
theta = np.linspace(0,2*np.pi,360)
radio1 = radio(0,1)   #z=0
x = np.linspace(-radio1,radio1,n)
y = np.linspace(-radio1,radio1,n)
Y = np.outer(x,np.ones(n))
X = np.transpose(np.outer(y,np.ones(n)))


p = np.outer(np.outer(x,np.ones(n)),np.ones(n))
q = np.array((p[:][:][:]))

print(p)
print(q)



M=np.ones((n,n))
for i in range(n):
  for j in range(n):
    if (X[i][j]**2+Y[i][j]**2)<r**2:
      M[i][j] = 0


# Implementación del método de diferencias finitas para la ecuación de difusión de calor, usando una función

# Implementar la variación de la generación de calor en la yema

# Implementar el cambio de volumen de los componentes del huevo.

a=